all: clean build run

clean: # remove data and binary folder
	rm -f state.json
	rm -f -r data

build: # compile to binary (if you use interpreter, then do not implement it)

run: # run your binary
	python3 src/dotabuffscrapper.py